version: '3.7'
services:
  api:
    image: liorkob/rest_api-project
    env_file:
      - .env
    container_name: rest_api-project
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT_RESTAPI=${SERVER_PORT_RESTAPI}
    ports:
      - 8080:8080
    depends_on:
      - postgres
  api_job:
    image: liorkob/job
    env_file:
      - .env
    container_name: rest_api_job-project
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT_JOB=${SERVER_PORT_JOB}
    ports:
      - 8081:8081
    depends_on:
      - postgres
  postgres:
    image: liorkob/database
    container_name: postgres_database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
