version: '3.7'
services:
  api:
    image: idoco138/rest_api-project
    env_file:
      - .env
    container_name: rest_api-project
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: idoco138/database
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432


#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - postgres
#    env_file:
#      - .env
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@admin.com
#      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#       - "80:80"